[build]
  base = "client"
  publish = "build"
  functions = "../api" # if your functions are in the root api folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[plugins]]
  package = "@netlify/plugin-functions-install-core"

